default_groups:
  - name: "rungroup"
    system: yes
    gid: "20000"
  - name: "developer"
    system: no
    gid: "9000"

default_users:
  - username: "developer"
    group: "developer"
    groups: ["docker", "wheel"]
    comment: "Default developer account"
    create_home: yes
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35343539636138643639383530353933653137386532633237653731366263323637396663663332
      6532633531653465616136373831386361653436663936390a303337373232623331373836396438
      31636666386532613233333165623933393138643039313663396135383663313236313962383832
      6662396434323438360a306163333534303534633832386261636537663935643061643164353430
      64393131616163623666616263353338396237363535376233323361623336373938333433376632
      3439383735353466353961626534623838333265613331303238
    authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtjo3fxl3gpQkywnXSZTVzJIzTiy3q8HCmPiyKVXCEQjPSwGN0s0T/sxHS3QqWvmWC0Qo3LQ/39rDhrNJOn+NGdIP6edEVdW4kfegI2n6nIQ0EyAKuMtx59S7nCSqo4hX9zaL3NhlBiKIYPAPxSmC91EiXEdQfMtn/dTHkZ5zWvbpDF7QHxaRwjxtqZhjoxWFLShijKmtijo0Tn9iiEHfUsS/cw+cJWM784k9MaCPdkzN9xewi4smpOS83rModhrZawCIqDRCa9K46T2K5XMQpac4pKvGrLbTCDwc0HzLR84IturpqF0b3ojriLZ1jP18rGEN5GP1Ij0aL0rH/iUaT survivorbat@MaartenPC"
    shell: "/bin/bash"
    uid: "9000"
  - username: "runuser"
    group: "rungroup"
    groups: ["docker"]
    create_home: yes
    comment: "Runuser responsible for running applications"
    shell: "/bin/bash"
    uid: "30000"
    password: ~
    authorized_key: ~
